### ISSUE TITLE
State of the Chat

### ISSUE THREAD

**Issue by InI4** [twilio/twilio-chat-demo-kotlin#8]
This is no bug report, this is bit like a letter of complaint.

Yea, I apologize, if this comes over rude, but it is getting just too much and I have no ideas where to place this, please tell me or forward appropriately. Pressure here is high to stop investigating Twilio Chat as viable.

- The chat is ridiculously huge, i.e. it contributes >50% of our apps download size.
- The chat contributes to more than 50% of apps crashes. Nearly all objects from the inner data structures seem to get null over time and sample code needs a surprising number null checks added all over the place, to avoid crashes.
- Chat notifications never worked reliably. State is like, after app has been used, chat notifications work like a few hours or so, i.e. firebase token renewal is a problem. But token renewal works for our apps own part.
- Chat is not running for long, i.e. some of our users have the app open for hours, but once the chat lib has lost contact, reconnection code from samples fails and chat stays disconnected, app restart required to fix it. 
- All of the above look a bit like lifecycle issues for native components.
- Chat finally stops to support Android 4.2.2, so there is not even hope to get anything of the above fixed for our customer base.

I do not expect anyone to cover this, I just post it. Read, digest and probably close.

**Comment by kristiyanP** [comment]
@ajtack @berkus You were talking about unofficial support of api19? 
This is twilio v4.0.3 on an emulator api19
```java
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.***, PID: 8596
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "newlocale" referenced by "libtwilio-rtd-native.so"...
        at java.lang.Runtime.load(Runtime.java:333)
        at java.lang.System.load(System.java:512)
        at com.twilio.chat.internal.ReLinker.loadLibrary(ReLinker.java:74)
        at com.twilio.chat.ChatClient.loadNativeLibraries(ChatClient.java:187)
        at com.twilio.chat.ChatClient.<init>(ChatClient.java:376)
        at com.twilio.chat.ChatClient.create(ChatClient.java:287)
```
For more information you may want to check stackoverflow:
https://stackoverflow.com/questions/44736135/ndk-clang-error-undefined-reference-to-localeconv

**Comment by berkus** [comment]
Going to close this
* Size issues are being addressed by steadily converting the SDK to more platform-native code.
* Reconnection issues must be pretty much all cleaned up by now.
* Android 4.2.2 is SO old by this moment we probably are beyond point of even thinking to support it.
